Backend
BC-CapstoneProjects/CookPal pull request #127
Opened 2022-04-14 00:29 UTC by elliotwe

2022-04-15 17:24 UTC, DavePie requested changes

2022-04-15 17:24 UTC, DavePie commented on app/src/main/java/bellevuecollege/edu/cookpal/network/DownloadRecipesMongoDB.kt
> +            println("this runs" )
This might be something I added at one point, but in general you don't want println() statements in main.

2022-04-15 17:24 UTC, DavePie commented on backend/spec/loadEnv.ts
> +const result2 = dotenv.config({
Should rename result2

2022-04-15 17:24 UTC, DavePie commented on backend/src/pre-start/index.ts
> +    const result2 = dotenv.config({
Would rename `result2` to something more descriptive

2022-04-15 17:24 UTC, DavePie commented on backend/src/repos/data-access.ts
> +    if (connection)
Perhaps look into using a formatter like Prettier

2022-04-15 17:24 UTC, DavePie commented on backend/src/repos/data-access.ts
> +function connectToMysql()
SQL is capatalized

2022-04-15 17:24 UTC, DavePie commented on backend/src/repos/data-access.ts
> +function putinPendingCodeUpdate(): Promise<any> {
putin -> putIn

2022-04-15 17:24 UTC, DavePie commented on backend/src/repos/data-access.ts
> +    connection = mysql.createConnection({
Are we using MySQL for anything?

2022-04-15 17:24 UTC, DavePie commented on backend/src/repos/recipe-repo.ts
> +
Remove excess spaces

2022-04-15 17:24 UTC, DavePie commented on backend/src/repos/recipe-repo.ts
> +async function getByTitle(title: string): Promise<Array<any>> {
would prefer for Array<any> to be typed ex: Array<IRecipe>

2022-04-15 17:24 UTC, DavePie commented on backend/src/routes/api.ts
> +            return res.status(OK).json({'info':'code update already in progress'});
Not entirely sure what is meant by code here.

2022-04-15 17:24 UTC, DavePie commented on backend/src/services/recipe-service.ts
> +async function getOne(id:string): Promise<IRecipe | null> {
Is two lines needed here? Perhaps I'm wrong but can you do:
return await .....;

2022-04-15 21:10 UTC, TonnyAn reviewed
Looks good, just seems like there's just some typos and needs some renaming variables just so the rest of us can understand what you were trying to do.

2022-04-15 21:10 UTC, TonnyAn commented on backend/build.ts
> +}
If you could add some small comments on what the functions generally do, what the params, and if they return anything what it returns that would help a lot. 

On some functions I see the comments and on others they aren't there.

2022-04-17 18:02 UTC, trang2020 approved these changes

2022-04-19 00:02 UTC, DavePie approved these changes

2022-04-19 00:04 UTC, merged

2022-04-19 17:49 UTC, elliotwe commented on backend/build.ts
> +}
I added more comments to the code.